Khushii-Arora/SmallWorkingProjects_Hacktoberfest22

Python Project/password_generator.py
Added a 'password generator' python project!
=> Added a python project!

JAVA Project/StonePaperScissor.java
Added the Stone Paper Scissor Game in Java.
=> Stone-Paper-Scissor Game in Java

JAVA Project/Temprature Converter
Temprature converter made using java, with simple concepts of object oriented language.
=> Temprature Converter in java

Python Project/Student Grading System.py
Signed-off-by: Aditya Mathur <61025539+AdityaMathur25@users.noreply.github.com>
=> Student grade system

JAVA Project/Rock Paper ScssiorGame.java
Added Rock paper scissors game
=> Rock paper scissors game

Python Project/Snake_game.py
=> Created Snake Game

Calculator-with-JS/custom.css, Calculator-with-JS/index.html, Calculator-with-JS/simplecalculator.js
Hey There,
I am adding a Simple Calculator With JS project to your component.
=> CalculatorWithJS

Tip-Calculator-with-js/index.html, Tip-Calculator-with-js/script.js, Tip-Calculator-with-js/style.css
This is a JavaScript tip calculator which can calculate the tip with proper mathematic calculation
=> JavaScript Tip calculator

Web Dev Projects/Counter/counter.css, Web Dev Projects/Counter/counter.html, Web Dev Projects/Counter/counter.js
Added a counter for convenience
=> Added a counter for convenience

Python Project/turtle race.py
turtle race game using turtle library of python
please accept the changes.
=> turtle race game

JAVA Project/Tic-Tac-Toe Game.java
=> Created Tic-Tac-Toe Game

Python Project/Scientific GUI Calculator.py
added Scientific GUI Calculator
=> Created Scientific GUI Calculator

BlockChain Project/NftMinter.sol
This solidity script will generate the NFTs on mostly any blockchain like polygon, or Ethereum.
=> Nft Generator

JS Project/timer/index.html, JS Project/timer/index.js, JS Project/timer/style.css
@Khushii-Arora , Hey please merge my contribution in your repo under hacktober label
it will be really helpful 
thank you.
=> CountDown Timer

Phone Number Location Tracker.py
Phone Number Location Tracker add this project
=> Hacktoberfest 2022

CPP Project/Car_Rental_system/README.md, CPP Project/Car_Rental_system/car_rental_system.cpp
**This is mini project , car rental system , the total code is written by C++ language **
=> ADD this mini_project A car_rental_system written c++.

JS Project/otpverification/index.html, JS Project/otpverification/script.js, JS Project/otpverification/style.css, Python Project/ping_pong_game.py
hello, I  have made  a code for otp verification which takes only digits as input.I just started learning web development so please accept this as my contribution for hacktoberfest
=> otp verification

Web Dev Projects/Modal Window/index.html, Web Dev Projects/Modal Window/style.css, Web Dev Projects/Order Summary Component/flip.js, Web Dev Projects/Order Summary Component/index.html, Web Dev Projects/Order Summary Component/style.css
added flip loading button in order summary component and attached a javascript file with it. and in modal window i have added a background shadow.
=> added flip-loading button

CPP Project/hotel_management.cpp
Created the hotel management code in cpp
=> Created Hotel_management.cpp

Python Project/text-to-sound.py
=> Test to Sound in python

JS Project/BMI Calculator/README.md, JS Project/BMI Calculator/index.html, JS Project/BMI Calculator/index.js, JS Project/BMI Calculator/styles.css
I have added Website to calculate BMI using HTML, CSS and JavaScript. Kindly consider the pull request.
=> Added Website to Calculate BMI 

Machine Learning Projects\Fake News Detection Using ML/FakeNews_Detection.ipynb
A detailed Machine Learning Project on Fake News Detection containing points such as accuracy,f1 score of top 3 models for it.
=> Fake News Detection Using ML

jarvis.py
=> Jarvis {AI assistance} 

Python Project/tictac.py
=> tic tac game

Python Project/PushNotificationSystem/main.py
This program notifies you to do a personalised task in a particular time period
=> PushNotificationApp

Beautiful game.html
Sir/mam I try to make a best game.
Please check
Thanks you
=> Beautifull game.html

Machine Learning Projects/Fake News Detection Using ML/FakeNews_Detection.ipynb
Folder named  'Machine Learning Projects\Fake News Detection Using ML/FakeNews_Detection.ipynb', was causing an error 
`error: invalid path 'Machine Learning Projects\Fake News Detection Using ML/FakeNews_Detection.ipynb'`
during cloning and switching branch. I fixed it using the command `config core.protectNTFS false`
=> Resolved error causing by invalid folder name 'Machine Learning Projects\Fake News Detection Using ML/FakeNews_Detection.ipynb'

Python Project/file.txt, Python Project/mailCounter.py
Add program to count mail types from list
=> Add file.txt and mailCounter.py

CPP Project/Blackjack/BLACKJ~1.CPP, CPP Project/Blackjack/README.md, CPP Project/Blackjack/Readme.md.txt
Menu based blackjack game on C++
=> BlackJack game

Python Project/CovidGraph.py
This will help you see graphically the covid cases across the globe
=> Added Covid graph python progtam

JAVA Project/magic.java
This is a magic card game.
In this game player choose a one number from 0 to 63. Then enter y/Y if your number is in the card else type n/N. Then last magic is programm is give you a number which player choose.
Happy Magic :)
=> magic card game

CPP Project/Sales Management System
Please accept my merge request
=> Create Sales Management System

CPP Project/Restraunt.cpp
Please accept my merge request on this restaurant billing in C++
=> This is my project on billing system of a fast food restraunt
